name: Build BarcodeDaemon (macOS ARM)

on:
  push:
    branches: [ "main" ]
    paths:
      - "main.py"
  pull_request:
    branches: [ "main" ]
    paths:
      - "main.py"

jobs:
  build-macos:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller \
            --name BarcodeDaemon \
            --onefile \
            --console \
            --add-data "DejaVuSans-Bold.ttf:." \
            --hidden-import=pkg_resources.py2_warn \
            --hidden-import=jaraco.text \
            main.py

      - name: Stage binary into package layout
        run: |
          OUT_ROOT="pack"
          TARGET_DIR="$OUT_ROOT/captureone-barcode-tool/Capture One Scripts/Background Scripts"
          mkdir -p "$TARGET_DIR"
          install -m 755 "dist/BarcodeDaemon" "$TARGET_DIR/BarcodeDaemon"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BarcodeDaemon-macos-arm64
          path: pack/captureone-barcode-tool
